spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8080
  servlet:
    context-path: /dna-task